import { fixelDisplay, fixelText, menlo } from './fonts';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${fixelDisplay.variable} ${fixelText.variable} ${menlo.variable} font-sans`}
    >
      <head>
        <meta name="apple-mobile-web-app-title" content="DropDrop" />
      </head>
      <body>{children}</body>
    </html>
  );
}
